Update `emea-crunch-gbl-emea-{env}.d_crunch_fr_stg_{env}.t_lpd_cosmaparfumerie_o`
Set SHEETNAME = "{sheetname}"
where  SHEETNAME is null AND RUN_ID = '{run_id}';


MERGE  `emea-crunch-gbl-emea-{env}.d_crunch_fr_dom_{env}.t_lpd_cosmaparfumerie_o` D
USING  (SELECT FORMAT_DATE('%Y%m%d', CAST( CONCAT(
              SUBSTR(periode, 1 , 4), 
              '-' ,
              SUBSTR(periode, 5 , 6), 
              '-' , 
              '01') 
             AS DATE
          )) AS PERIOD_START_DATE,
         FORMAT_DATE('%Y%m%d',  DATE_SUB(DATE_TRUNC(DATE_ADD(CAST(
            CONCAT(
              SUBSTR(periode, 1 , 4), 
              '-' ,
              SUBSTR(periode, 5 , 6), 
              '-' , 
              '01') 
             AS DATE
          ), INTERVAL 1 MONTH), MONTH), INTERVAL 1 DAY)) AS PERIOD_END_DATE, LOREAL_MARKET_FLAG, MARQUE, VALEUR, PERIODE, RUN_ID FROM (
select 'L' AS LOREAL_MARKET_FLAG,
CASE
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'JANVIER') is True then CONCAT(A.YEAR, '01')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'FEVRIER') is True then CONCAT(A.YEAR, '02')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'MARS') is True then CONCAT(A.YEAR, '03')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'AVRIL') is True then CONCAT(A.YEAR, '04')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'MAI') is True then CONCAT(A.YEAR, '05')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'JUIN') is True then CONCAT(A.YEAR, '06')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'JUILLET') is True then CONCAT(A.YEAR, '07')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'AOUT') is True then CONCAT(A.YEAR, '08')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'SEPTEMBRE') is True then CONCAT(A.YEAR, '09')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'OCTOBRE') is True then CONCAT(A.YEAR, '10')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'NOVEMBRE') is True then CONCAT(A.YEAR, '11')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'DECEMBRE') is True then CONCAT(A.YEAR, '12') ELSE NULL END PERIODE, CAST(REPLACE(REPLACE(VALEUR, '€',''),',','.') as FLOAT64) as VALEUR,
CASE
WHEN MARQUE LIKE 'TOTAL%' THEN ''
ELSE MARQUE END AS MARQUE,  RUN_ID
  from `emea-crunch-gbl-emea-{env}.d_crunch_fr_stg_{env}.t_lpd_cosmaparfumerie_o`
 UNPIVOT(VALEUR FOR PERIODE_MOIS IN (JANVIER,	FEVRIER,	MARS,	AVRIL,	MAI,	JUIN,	JUILLET,	AOUT,	SEPTEMBRE,	OCTOBRE,	NOVEMBRE,	DECEMBRE))
 CROSS JOIN (
   SELECT REGEXP_EXTRACT(MARQUE, r'[0-9]{{4}}') AS YEAR FROM  `emea-crunch-gbl-emea-{env}.d_crunch_fr_stg_{env}.t_lpd_cosmaparfumerie_o`  WHERE REGEXP_EXTRACT(MARQUE, r'[0-9]{{4}}') IS NOT NULL
   AND RUN_ID = '{run_id}' AND SHEETNAME = "L'OREAL LUXE"
 ) A
 WHERE MARQUE IS NOT NULL AND MARQUE != 'TOTAL' and SHEETNAME = "L'OREAL LUXE"
 AND RUN_ID = '{run_id}'
 
 UNION ALL
 
 select 'M' AS LOREAL_MARKET_FLAG,CASE
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'JANVIER') is True then CONCAT(A.YEAR, '01')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'FEVRIER') is True then CONCAT(A.YEAR, '02')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'MARS') is True then CONCAT(A.YEAR, '03')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'AVRIL') is True then CONCAT(A.YEAR, '04')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'MAI') is True then CONCAT(A.YEAR, '05')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'JUIN') is True then CONCAT(A.YEAR, '06')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'JUILLET') is True then CONCAT(A.YEAR, '07')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'AOUT') is True then CONCAT(A.YEAR, '08')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'SEPTEMBRE') is True then CONCAT(A.YEAR, '09')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'OCTOBRE') is True then CONCAT(A.YEAR, '10')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'NOVEMBRE') is True then CONCAT(A.YEAR, '11')
WHEN REGEXP_CONTAINS(PERIODE_MOIS, r'DECEMBRE') is True then CONCAT(A.YEAR, '12') ELSE NULL END PERIODE, CAST(REPLACE(REPLACE(VALEUR, '€',''),',','.') as FLOAT64) as VALEUR,
CASE
WHEN MARQUE LIKE 'TOTAL%' THEN ''
ELSE MARQUE END AS MARQUE,  RUN_ID
  from `emea-crunch-gbl-emea-{env}.d_crunch_fr_stg_{env}.t_lpd_cosmaparfumerie_o`
 UNPIVOT(VALEUR FOR PERIODE_MOIS IN (JANVIER,	FEVRIER,	MARS,	AVRIL,	MAI,	JUIN,	JUILLET,	AOUT,	SEPTEMBRE,	OCTOBRE,	NOVEMBRE,	DECEMBRE))
 CROSS JOIN (
   SELECT REGEXP_EXTRACT(MARQUE, r'[0-9]{{4}}') AS YEAR FROM  `emea-crunch-gbl-emea-{env}.d_crunch_fr_stg_{env}.t_lpd_cosmaparfumerie_o` WHERE REGEXP_EXTRACT(MARQUE, r'[0-9]{{4}}') IS NOT NULL
   AND RUN_ID = '{run_id}' AND SHEETNAME =  "SITE COSMA"
 ) A
 WHERE MARQUE IS NOT NULL AND SHEETNAME = "SITE COSMA"
 AND RUN_ID = '{run_id}'
 )
)  S
ON  D.PERIODE = S.PERIODE 
AND UPPER(D.MARQUE)=UPPER(S.MARQUE) 
AND D.RUN_ID IS NULL
when  MATCHED then
update set
D.VALEUR	= 	S.VALEUR,
D.UPDATE_DATETIME	= current_datetime()
when not MATCHED --AND (MARQUE is not null and SHEETNAME = "L'OREAL LUXE")
AND VALEUR != 0.0 and VALEUR is not null  then
insert (MARQUE, VALEUR,PERIODE,  INSERT_DATETIME, UPDATE_DATETIME, RETAILER, PERIOD_START_DATE, PERIOD_END_DATE, LOREAL_MARKET_FLAG, RUN_ID)
values (UPPER(MARQUE), VALEUR, PERIODE, current_datetime(), current_datetime(), "COSMA PARFUMERIE", PERIOD_START_DATE, PERIOD_END_DATE, LOREAL_MARKET_FLAG, RUN_ID);